# Generated by Django 4.1.7 on 2023-03-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(blank=True, max_length=10, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=12, null=True)),
                ('model', models.CharField(blank=True, max_length=12, null=True)),
                ('engine_cc', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
