# Generated by Django 4.1.7 on 2023-03-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
