# Generated by Django 4.1.7 on 2023-03-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_cc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
