# Generated by Django 4.1.7 on 2023-03-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_car_engine_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_cc',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
